class Department {
  static final List<String> departments = [
    "SECRETARIA MUNICIPAL DE ADMINISTRAÇÃO E RECURSOS HUMANOS",
    "SECRETARIA MUNICIPAL DE AGRICULTURA E MEIO AMBIENTE",
    "SECRETARIA MUNICIPAL DE ASSISTÊNCIA SOCIAL E HABITAÇÃO",
    "SECRETARIA MUNICIPAL DE CIÊNCIA E TECNOLOGIA",
    "SECRETARIA MUNICIPAL DE CULTURA E JUVENTUDE",
    "SECRETARIA MUNICIPAL DE DESENVOLVIMENTO ECONÔMICO",
    "SECRETARIA MUNICIPAL DE EDUCAÇÃO",
    "SECRETARIA MUNICIPAL DE ESPORTE E LAZER",
    "SECRETARIA MUNICIPAL DE FAZENDA",
    "SECRETARIA MUNICIPAL DE FINANÇAS",
    "SECRETARIA MUNICIPAL DE GABINETE",
    "SECRETARIA MUNICIPAL DE OBRAS E VIAÇÃO",
    "SECRETARIA MUNICIPAL DE PLANEJAMENTO",
    "SECRETARIA MUNICIPAL DE SAÚDE",
    "SECRETARIA MUNICIPAL INTEGRADA DE APOIO À SEGURANÇA",
  ];
}
